export const RoleCodes = {
  ADMIN: "ADMIN",
  EMPLOYEE: "EMPLOYEE",
  COORDINATOR: "COORDINATOR",
  IT_LEADER: "IT_LEADER",
  IT_STAFF: "IT_STAFF",
};

export const StatusCodes = {
  NEW: "NEW",
  WAITING_COORDINATOR: "WAITING_COORDINATOR",
  ACCEPTED: "ACCEPTED",
  NEED_INFO: "NEED_INFO",
  CLASSIFIED: "CLASSIFIED",
  WAITING_IT_ASSIGNMENT: "WAITING_IT_ASSIGNMENT",
  ASSIGNED: "ASSIGNED",
  IN_PROGRESS: "IN_PROGRESS",
  WAITING_INTERNAL_REVIEW: "WAITING_INTERNAL_REVIEW",
  WAITING_USER_CONFIRMATION: "WAITING_USER_CONFIRMATION",
  REWORK: "REWORK",
  COMPLETED: "COMPLETED",
};

export const AssignmentType = {
  COORDINATOR: "COORDINATOR",
  IT_GROUP: "IT_GROUP",
  IT_STAFF: "IT_STAFF",
};

export const AttachmentContextType = {
  REQUEST: "REQUEST",
  PROGRESS: "PROGRESS",
  COMMENT: "COMMENT",
  FEEDBACK: "FEEDBACK",
};
